wandb_version: 1

agent:
  value: AgentTestSet
att_kernel:
  value: 1
channel_attention:
  value: true
data_folder:
  value: ./data/test/
data_mode:
  value: test
gpu_device:
  value: 0
mode:
  value: test
model_path:
  value: 0qu12swp
modelname:
  value: PerfUNet
reduce:
  value: AttentionModule
seed:
  value: 1
temporal_attention:
  value: true
