program: main.py
method: grid
parameters:
  gpu_device:
    values:
      - 0
  seed:
    values:
      - 1
      - 2
      - 3
      - 4
      - 5
  agent:
    values:
      - 'Agent'
  modelname:
    values:
      - 'PerfUNetVariant'
  reduce:
    values:
      - 'MeanModule'
  fold:
    values:
      - 'fold_a'
      - 'fold_b'
      - 'fold_c'
      - 'fold_d'
command:
  - ${env}
  - python
  - ${program}
  - configs/config.json